apiVersion: apps.my.domain/v1alpha1
kind: ProgressiveDeployment
metadata:
  labels:
    app.kubernetes.io/name: bg-switch
    app.kubernetes.io/managed-by: kustomize
  name: progressivedeployment-sample
spec:
  # TODO(user): Add fields here
