apiVersion: apps.my.domain/v1alpha1
kind: ProgressiveDeployment
metadata:
  name: demo-app-progressive
  namespace: default
  labels:
    app: demo-app
spec:
  # Target deployment to progressively update
  targetDeployment: demo-app
  
  # Canary steps as percentages
  canarySteps: [25, 50, 75, 100]
  
  # Wait 30 seconds at each step before analyzing
  stepDuration: 30s
  
  # Automatically promote if metrics are healthy
  autoPromote: true
  
  # Prometheus metrics configuration
  metrics:
    # Prometheus URL (optional, defaults to in-cluster)
    prometheusUrl: "http://prometheus.monitoring.svc.cluster.local:9090"
    
    # Error rate threshold
    errorRate:
      query: 'rate(http_requests_total{job="demo-app",status=~"5.."}[5m])'
      threshold: 0.01  # 1% error rate max
    
    # Latency threshold (p95)
    latency:
      query: 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="demo-app"}[5m]))'
      threshold: 0.5  # 500ms max
